# Numpy Part 02

# Day 13

# Slicing of numpy arrays 

In [1]:
import numpy as np

# Slicing in 1-D array

In [2]:
arr = np.array([1,2,3,4,5])
print(arr[1:5])

[2 3 4 5]


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:2])

[1 2]


# Slicing in 2-D array

In [13]:
a = np.array([[10,20,30,40,50],[40,50,60,70,80]])
print(a[0,0:6])
print(a[1,1:6])

[10 20 30 40 50]
[50 60 70 80]


In [16]:
import numpy as np

In [17]:
Data Type in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for intergers,
i - integer 
b - boolean
u - unsigned integer
f - float 
c - complex
m - timedelta
M - datetime
0 - object 
s - string
u - unicode string
v - fixed chunk of memory for other type (void)


SyntaxError: invalid syntax (1950509848.py, line 1)

# Cheaking the data type in n array

In [18]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [21]:
arr = np.array(['animals', 'bat', 'cat'])
print(arr.dtype)

<U7


# Creating arrays with a defined data type

In [30]:
import numpy as np

In [47]:
arr = np.array([1,2,3,4], dtype = 's')
print(arr)
print(arr.dtype)

TypeError: data type 's' not understood

# Create array with data types 4 bytes integer

In [48]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy array Shape

the shape of an array is the number of elements in each dimension

# Print the Shape of a 2D Array

In [50]:
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr.shape)

(2, 4)


# 3D Array

In [52]:
arr = np.array([[[1,2,3,4],[6,7,8,9],[10,20,30,50]]])
print(arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

# For 1D Array

In [55]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# For 2D Array

In [60]:
arr1 = np.array([[1,2],[4,5]])

arr2 = np.array([[3,6],[19,7]])

arr = np.concatenate((arr1,arr2),axis = 1)

print(arr)

[[ 1  2  3  6]
 [ 4  5 19  7]]


In [61]:
arr1 = np.array([[1,2],[4,5]])

arr2 = np.array([[3,6],[19,7]])

arr = np.concatenate((arr1,arr2),axis = 0)

print(arr)

[[ 1  2]
 [ 4  5]
 [ 3  6]
 [19  7]]


# Splitting Numpy arrays

# splitting the array in 3 parts

In [62]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# splitting the array in 4 parts

In [63]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Revel & flatten

# converts multimensional array into 1D array

In [65]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is ",m.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3


In [66]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is ",m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
now the new dimension is  1


In [67]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is ",m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
now the new dimension is  1


In [68]:
c = np.array([[[[1,2,3],[4,5,6],[6,5,6],[1,4,5]]]])
print(c)
print("dimension is ",c.ndim)
d = c.ravel()
print(d)
print("now the new dimension is ",d.ndim)

[[[[1 2 3]
   [4 5 6]
   [6 5 6]
   [1 4 5]]]]
dimension is  4
[1 2 3 4 5 6 6 5 6 1 4 5]
now the new dimension is  1


In [69]:
c = np.array([[[[1,2,3],[4,5,6],[6,5,6],[1,4,5]]]])
print(c)
print("dimension is ",c.ndim)
d = c.flatten()
print(d)
print("now the new dimension is ",d.ndim)

[[[[1 2 3]
   [4 5 6]
   [6 5 6]
   [1 4 5]]]]
dimension is  4
[1 2 3 4 5 6 6 5 6 1 4 5]
now the new dimension is  1


# Unique Function 

In [70]:
k = np.array([1,2,3,1,3,2,3,4,5,6,7,8,9,11,12,23,45,2,5,12])
print(k)
x = np.unique(k)
print(x)

[ 1  2  3  1  3  2  3  4  5  6  7  8  9 11 12 23 45  2  5 12]
[ 1  2  3  4  5  6  7  8  9 11 12 23 45]


In [72]:
k = np.array([1,2,3,1,3,2,3,4,5,6,7,8,9,11,12,23,45,2,5,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[ 1  2  3  1  3  2  3  4  5  6  7  8  9 11 12 23 45  2  5 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 23, 45]), array([ 0,  1,  2,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16], dtype=int64), array([2, 3, 3, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1], dtype=int64))


# Delete

In [73]:
a = np.array([11,12,13,14])
d = np.delete(a,[1])
print(d)

[11 13 14]


In [79]:
x = np.array([[2,3,4,5,6],[3,5,6,7,7,],[2,4,5,56,6]])
print(x)
m = np.delete(x, 1, axis = 1)
print()
print(m)

[[ 2  3  4  5  6]
 [ 3  5  6  7  7]
 [ 2  4  5 56  6]]

[[ 2  4  5  6]
 [ 3  6  7  7]
 [ 2  5 56  6]]
