# Numpy Library

In [3]:
import numpy as np

In [57]:
print(np.__version__)

1.21.5


# Create a Numpy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray. 


We can create a NumPy ndarray object by using the array() function.

In [58]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

# Use a tuple to create a NumPy array: 

In [60]:
import numpy as np 

In [62]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimension in array

0-D Arrays 0-D arrays, scalars, are the elements in an array.each value in an array is o 0-D
array.

Create a 0-D array with value 20

In [64]:
arr = np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


# 1 dimension array

1-D Arrays 0-D array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [7]:
arr = np.array([1,2,4,5,6])
print(arr)
print(arr.ndim)

[1 2 4 5 6]
1


# 2 dimension array

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [9]:
arr = np.array([[1.2,2.6,3.5],[4.6,5.6,6.7]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1.2 2.6 3.5]
 [4.6 5.6 6.7]]
<class 'numpy.ndarray'>
2


# 3 dimension array

Am array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [13]:
import numpy as np

In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


# Check number of Dimension?

In [18]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions. 

When the array is created, you can define the number of dimensions by using the ndmin argument. 

# Create an array with 5 dimensions as verify that it has 5 dimenstions:

In [25]:
arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)
print('number of dimesion:' , arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimesion: 5


In [26]:
a = np.array([[[[1,2,3,4]]]])
print(a)
print(a.ndim)

[[[[1 2 3 4]]]]
4


# Numpy array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referrring to its index number. 

The indexes in NumPy arrays start with, 0 meaning that the element has index 0 , and the second has index 1 etc.

# Get the first element from the following array:

In [27]:
arr = np.array([1,2,3,4])
print(arr[0])


1


# Get third and sixth and 8th elements from the following array and add them.

In [29]:
m = np.array([23,45,66,78,23,56,67,89,90])
print("the second element is ", m[2])
print("the sixth element is ",m[5])
print("the 8th element is ",m[7])
print("sum of this element",m[2]+m[5]+m[7])

the second element is  66
the sixth element is  56
the 8th element is  89
sum of this element 211


# 2-D Array Indexing

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [31]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element on 1st row :', arr[0,3])

4th element on 1st row : 4


In [32]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('1st element on 2nd row :', arr[1,0])

1st element on 2nd row : 6


In [33]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("last element on 2nd row:", arr[1,4])

last element on 2nd row: 10


# add the element of row 1 and last element 

In [34]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("1st element of 1st row :",arr[0,0])
print("last element of 2nd row:", arr[1,4])
print("The Sum is = ",arr[0,0]+arr[1,4])

1st element of 1st row : 1
last element of 2nd row: 10
The Sum is =  11


# Access of 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

# Access the third element of the second array of the first array:

In [37]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [38]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,0,2])

3


In [39]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,3,2])

12


In [56]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6
